- name: installing nginx
  hosts: web
  become: yes
  tasks:
  - name:
    ansible.builtin.package:
     name: nginx
     state: present
  - name:
    anisble.builtin.service:
     name: nginx
     state: started
     
